/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CookingFun;

import javax.swing.JLabel;

/**
 *
 * @author Hassan ul haq
 */
public class ChickenPizza extends javax.swing.JFrame {

        // these boolean var are used for enabling and disabling the ingredients(labels)

    boolean d, s, c, p, o, ch;
    
    // score counting 
    protected int count;
    
        //  used for calculting the clicks on ingredient

    int click;
    
    // mouse pressed on the scrren 
 
    int xmouse1;
    int ymouse1;
    
        // mouse dragged on the screen  

    int x2;
    int y2;
    
          // mouse pressed on the object(ingredient)

    int xdough;
    int ydough;
    int xcheese;
    int ycheese;
    int xsauce;
    int ysauce;
    int xpepperoni;
    int ypepperoni;
    int xchicken;
    int ychicken;
    int xolives;
    int yolives;

    /**
     * Creates new form ChickenPizza
     */
    public ChickenPizza() {
        initComponents();
        click = 0;
        count = 0;
        d = true;
        c = false;
        s = false;
        p = false;
        o = false;
        ch = false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recepie = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        olives = new javax.swing.JLabel();
        chicken = new javax.swing.JLabel();
        pepperoni = new javax.swing.JLabel();
        cheese = new javax.swing.JLabel();
        sauce = new javax.swing.JLabel();
        dough = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jback = new javax.swing.JLabel();
        cutting_board = new javax.swing.JLabel();
        bake = new javax.swing.JButton();
        oven = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        recepie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recepie.setForeground(new java.awt.Color(102, 204, 0));
        recepie.setText("RECEPIE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        olives.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/olive.png"))); // NOI18N
        olives.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                olivesMouseDragged(evt);
            }
        });
        olives.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                olivesMousePressed(evt);
            }
        });
        jPanel1.add(olives);
        olives.setBounds(340, 370, 40, 50);

        chicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chicken.png"))); // NOI18N
        chicken.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                chickenMouseDragged(evt);
            }
        });
        chicken.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chickenMousePressed(evt);
            }
        });
        jPanel1.add(chicken);
        chicken.setBounds(540, 370, 70, 50);

        pepperoni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pepperino.png"))); // NOI18N
        pepperoni.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pepperoniMouseDragged(evt);
            }
        });
        pepperoni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pepperoniMousePressed(evt);
            }
        });
        jPanel1.add(pepperoni);
        pepperoni.setBounds(440, 360, 80, 60);

        cheese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cheese.png"))); // NOI18N
        cheese.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cheeseMouseDragged(evt);
            }
        });
        cheese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cheeseMousePressed(evt);
            }
        });
        jPanel1.add(cheese);
        cheese.setBounds(130, 360, 90, 60);

        sauce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pizza sauce.png"))); // NOI18N
        sauce.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sauceMouseDragged(evt);
            }
        });
        sauce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sauceMousePressed(evt);
            }
        });
        jPanel1.add(sauce);
        sauce.setBounds(230, 360, 70, 70);

        dough.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dough.png"))); // NOI18N
        dough.setText(" ");
        dough.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                doughMouseDragged(evt);
            }
        });
        dough.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                doughMousePressed(evt);
            }
        });
        jPanel1.add(dough);
        dough.setBounds(20, 370, 80, 40);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/backOrange.PNG"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(520, 120, 80, 70);

        jback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jback.setForeground(new java.awt.Color(51, 204, 0));
        jback.setText("Back");
        jPanel1.add(jback);
        jback.setBounds(530, 200, 100, 30);

        cutting_board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cutting-board128.png"))); // NOI18N
        jPanel1.add(cutting_board);
        cutting_board.setBounds(160, 210, 130, 80);

        bake.setBackground(new java.awt.Color(255, 153, 153));
        bake.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bake.setForeground(new java.awt.Color(0, 102, 102));
        bake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Flame.png"))); // NOI18N
        bake.setText("Bake");
        bake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakeActionPerformed(evt);
            }
        });
        jPanel1.add(bake);
        bake.setBounds(350, 210, 100, 40);

        oven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oven.png"))); // NOI18N
        jPanel1.add(oven);
        oven.setBounds(330, 170, 160, 120);

        background.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kitchen.PNG"))); // NOI18N
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        jPanel1.add(background);
        background.setBounds(0, 0, 640, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        xmouse1 = evt.getX();
        ymouse1 = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        int xdrag1 = evt.getXOnScreen();
        int ydrag1 = evt.getYOnScreen();
        x2 = xdrag1;
        y2 = ydrag1;
    }//GEN-LAST:event_backgroundMouseDragged

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        PizzaMenu mf = new PizzaMenu();

        mf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void doughMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doughMousePressed
        click++;
        if (d) {
            xdough = evt.getX();
            ydough = evt.getY();
            if (click == 1) {
                count++;
            }

        } else {
            count--;
        }
    }//GEN-LAST:event_doughMousePressed

    private void doughMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doughMouseDragged
        if (d) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            dough.setLocation((x - x2) - (xdough - xmouse1), (y - y2) - (ydough - ymouse1));
            dough.setVisible(true);
            d = true;
            s = true;
            c = false;
            p = false;
            ch = false;
            o = false;
        }
        click = 0;
    }//GEN-LAST:event_doughMouseDragged

    private void sauceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sauceMousePressed
        click++;
        if (s) {
            xsauce = evt.getX();
            ysauce = evt.getY();
            if (click == 1) {
                count++;
            }

        } else {
            count--;
        }
    }//GEN-LAST:event_sauceMousePressed

    private void sauceMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sauceMouseDragged
        if (s) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            sauce.setLocation((x - x2) - (xsauce - xmouse1), (y - y2) - (ysauce - ymouse1));
            sauce.setVisible(true);
            d = true;
            s = true;
            c = true;
            p = false;
            ch = false;
            o = false;
        }
        click = 0;
    }//GEN-LAST:event_sauceMouseDragged

    private void cheeseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cheeseMousePressed
        click++;
        if (c) {
            xcheese = evt.getX();
            ycheese = evt.getY();
            if (click == 1) {
                count++;
            }

        } else {
            count--;
        }
    }//GEN-LAST:event_cheeseMousePressed

    private void cheeseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cheeseMouseDragged
        if (c) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            cheese.setLocation((x - x2) - (xcheese - xmouse1), (y - y2) - (ycheese - ymouse1));
            cheese.setVisible(true);
            d = true;
            s = true;
            c = true;
            p = true;
            ch = false;
            o = false;
        }
        click = 0;
    }//GEN-LAST:event_cheeseMouseDragged

    private void pepperoniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pepperoniMousePressed
        click++;
        if (p) {
            xpepperoni = evt.getX();
            ypepperoni = evt.getY();
            if (click == 1) {
                count++;
            }

        } else {
            count--;
        }
    }//GEN-LAST:event_pepperoniMousePressed

    private void pepperoniMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pepperoniMouseDragged
        if (p) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            pepperoni.setLocation((x - x2) - (xpepperoni - xmouse1), (y - y2) - (ypepperoni - ymouse1));
            pepperoni.setVisible(true);
            d = true;
            s = true;
            c = true;
            p = true;
            ch = true;
            o = false;
        }
        click = 0;
    }//GEN-LAST:event_pepperoniMouseDragged

    private void chickenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chickenMousePressed
        click++;
        if (ch) {
            xchicken = evt.getX();
            ychicken = evt.getY();
            if (click == 1) {
                count++;
            }

        } else {
            count--;
        }
    }//GEN-LAST:event_chickenMousePressed

    private void chickenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chickenMouseDragged
        if (ch) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            chicken.setLocation((x - x2) - (xchicken - xmouse1), (y - y2) - (ychicken - ymouse1));
            chicken.setVisible(true);
            d = true;
            s = true;
            c = true;
            p = true;
            ch = true;
            o = true;
        }
        click = 0;
    }//GEN-LAST:event_chickenMouseDragged

    private void olivesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olivesMousePressed
        click++;
        if (o) {
            xolives = evt.getX();
            yolives = evt.getY();
            if (click == 1) {
                count++;
            }

        } else {
            count--;
        }
    }//GEN-LAST:event_olivesMousePressed

    private void olivesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olivesMouseDragged
        if (o) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            olives.setLocation((x - x2) - (xolives - xmouse1), (y - y2) - (yolives - ymouse1));
            olives.setVisible(true);
            d = true;
            s = true;
            c = true;
            p = true;
            ch = true;
            o = true;
        }
        click = 0;
    }//GEN-LAST:event_olivesMouseDragged

    private void bakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakeActionPerformed
       // if all the ingrediets true only then bake button will be enabled

        if (d && s && c && p && ch && o) {
            BakedChickenPizza bp = new BakedChickenPizza(count);
            bp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_bakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChickenPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChickenPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChickenPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChickenPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChickenPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton bake;
    private javax.swing.JLabel cheese;
    private javax.swing.JLabel chicken;
    private javax.swing.JLabel cutting_board;
    private javax.swing.JLabel dough;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jback;
    private javax.swing.JLabel olives;
    private javax.swing.JLabel oven;
    private javax.swing.JLabel pepperoni;
    private javax.swing.JLabel recepie;
    private javax.swing.JLabel sauce;
    // End of variables declaration//GEN-END:variables
}
