/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CookingFun;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author toshiba
 */
public class Cupcake extends javax.swing.JFrame {
     private Connection con;
    private Statement st;
    private ResultSet rs;
    
    boolean c,cr,ch;
  protected int count;
   int click;
     String cond;
int xmouse1;
    int ymouse1;
    int x2;
    int y2;
    int xmousecake;
    int ymousecake;
    int xmousecherry;
    int ymousecherry;
    int xmousecre;
    int ymousecre;
    /**
     * Creates new form Cupcake
     */
    public Cupcake() {
        initComponents();
        click = 0;
        count = 0;
        c = true;
        cr = false;
       
        ch = false;
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cherry = new javax.swing.JLabel();
        wippingcream = new javax.swing.JLabel();
        cupcake = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        done = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(null);

        cherry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/cherry.png"))); // NOI18N
        cherry.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cherryMouseDragged(evt);
            }
        });
        cherry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cherryMousePressed(evt);
            }
        });
        jPanel1.add(cherry);
        cherry.setBounds(160, 390, 50, 50);

        wippingcream.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/cupcake cream.png"))); // NOI18N
        wippingcream.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                wippingcreamMouseDragged(evt);
            }
        });
        wippingcream.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                wippingcreamMousePressed(evt);
            }
        });
        jPanel1.add(wippingcream);
        wippingcream.setBounds(290, 350, 130, 120);

        cupcake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/cup.png"))); // NOI18N
        cupcake.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cupcakeMouseDragged(evt);
            }
        });
        cupcake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cupcakeMousePressed(evt);
            }
        });
        jPanel1.add(cupcake);
        cupcake.setBounds(470, 360, 110, 0);

        back.setBackground(new java.awt.Color(255, 255, 0));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(540, 80, 51, 50);

        done.setBackground(new java.awt.Color(255, 255, 0));
        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/done.png"))); // NOI18N
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        jPanel1.add(done);
        done.setBounds(540, 250, 60, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/cutting-board128.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 210, 128, 80);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/Cap.PNG"))); // NOI18N
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        jPanel1.add(background);
        background.setBounds(70, 30, 610, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       CakeMenu pm = new CakeMenu();
         pm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
       if (c&& cr && ch ) {            
            try {
                 String urlDB = System.getProperty("user.dir").concat("\\records1.accdb");

            con = DriverManager.getConnection("jdbc:ucanaccess://" + urlDB + ";memory=true");
            st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery("select* from records");
                 while(rs.next()){
                PreparedStatement s = con.prepareStatement("UPDATE records SET Score=? where Name='"+ login.name +"'"); 
           if (count > 0 && count<3) {
               s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                    
                Successful_score S = new Successful_score(count);
                S.setVisible(true);
                this.dispose();
            } else if(count<=0){
                s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                    
                cond="ck";
                LooserFrame l = new LooserFrame(count,cond);
                l.setVisible(true);
                this.dispose();
            }
             else if(count>2)
               {s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                    
           Winner w= new Winner();
            w.setVisible(true);
            this.dispose();
     }
                 } } catch (SQLException ex) {
                Logger.getLogger(SimpleBurger.class.getName()).log(Level.SEVERE, null, ex);
            }
         finally{
        try {
             con.close();
             st.close();
             rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(BakedPlainPizza.class.getName()).log(Level.SEVERE, null, ex);
        } 
            }
        }
    }//GEN-LAST:event_doneActionPerformed

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
       xmouse1= evt.getX();
       ymouse1 =evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        int xdrag1=evt.getXOnScreen();
            int ydrag1=evt.getYOnScreen();
             x2=xdrag1;
             y2=ydrag1;
    }//GEN-LAST:event_backgroundMouseDragged

    private void cupcakeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cupcakeMousePressed
       click++;
       if(c){
        xmousecake= evt.getX();
       ymousecake =evt.getY();
       if(click==1)
           count++;
       }
       else
           count--;
    }//GEN-LAST:event_cupcakeMousePressed

    private void cupcakeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cupcakeMouseDragged
       if(c){
        int x = evt.getXOnScreen();
          int y = evt.getYOnScreen();
         cupcake.setLocation((x-x2)-(xmousecake-xmouse1), (y-y2)-(ymousecake-ymouse1));
           cupcake.setVisible(true);
           c = true;
        
        cr = true;
        ch=false;
       }
       click=0;
    }//GEN-LAST:event_cupcakeMouseDragged

    private void cherryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cherryMousePressed
       click++;
       if(ch){
        xmousecherry= evt.getX();
       ymousecherry =evt.getY();
       if(click==1)
           count++;
       }
       else
           count--;
    }//GEN-LAST:event_cherryMousePressed

    private void cherryMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cherryMouseDragged
       if(ch){
        int x = evt.getXOnScreen();
          int y = evt.getYOnScreen();
         cherry.setLocation((x-x2)-(xmousecherry-xmouse1), (y-y2)-(ymousecherry-ymouse1));
           cherry.setVisible(true);
            c = true;
        
        cr = true;
        ch=true;
       }
       click=0;
    }//GEN-LAST:event_cherryMouseDragged

    private void wippingcreamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wippingcreamMousePressed
      click++;
      if(cr){
       xmousecre= evt.getX();
       ymousecre =evt.getY();
       if(click==1)
           count++;
           }
      else
          count--;
    }//GEN-LAST:event_wippingcreamMousePressed

    private void wippingcreamMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wippingcreamMouseDragged
       if(cr){
        int x = evt.getXOnScreen();
          int y = evt.getYOnScreen();
         wippingcream.setLocation((x-x2)-(xmousecre-xmouse1), (y-y2)-(ymousecre-ymouse1));
           wippingcream.setVisible(true);
           c = true;
        
        cr = true;
        ch=true;
       }
       click=0;
    }//GEN-LAST:event_wippingcreamMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cupcake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cupcake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cupcake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cupcake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cupcake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel cherry;
    private javax.swing.JLabel cupcake;
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel wippingcream;
    // End of variables declaration//GEN-END:variables
}
