/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CookingFun;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author toshiba
 */
public class Fishburger extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs;

// these boolean var are used for enabling and disabling the ingredients(labels)
    boolean b, t, p, c;
     // score counting 
    protected int count;
    //  used for calculting the clicks on ingredient
    int click;
    
    // this var is used for looser frame's try again button 
    // we use it for transfering the string to looser frame 
    // suppose if user is playing onfish burger interface and he lost with the score 0 and < 0 
    // then he want to try it again , for this purpose to show him the fish burger interface again 
    // so we are passing the string alphabet as the "type of burger" user is playing ,eg: for king "k" , for fish burger "f" etc
    // and then for making same burger again he will get the same interface again
    String cond;

// mouse pressed on the scrren
    int xmouse1;
    int ymouse1;
    
     // mouse dragged on the screen 
    int x2;
    int y2;
    
     // mouse pressed on the object(ingredient)
    int xmousebottom;
    int ymousebottom;
    int xmousetop;
    int ymousetop;
    int xmousepettey;
    int ymousepettey;
    int xmousechee;
    int ymousechee;


    /**
     * Creates new form Fishburger
     */
    public Fishburger() {

        initComponents();
        this.setSize(825, 550);
        click = 0;
        count = 0;
        b = true;
        t = false;
        c = false;
        p = false;

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        done = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        top = new javax.swing.JLabel();
        cheese = new javax.swing.JLabel();
        pettey = new javax.swing.JLabel();
        bottom = new javax.swing.JLabel();
        cutting = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/backYellow.PNG"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/doneYellow.PNG"))); // NOI18N
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 51));
        jLabel12.setText("BACK");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 51));
        jLabel13.setText("DONE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3);
        jPanel3.setBounds(660, 0, 150, 390);

        top.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/bun top.png"))); // NOI18N
        top.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topMouseDragged(evt);
            }
        });
        top.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topMousePressed(evt);
            }
        });
        jPanel4.add(top);
        top.setBounds(50, 420, 113, 70);

        cheese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/cheese.png"))); // NOI18N
        cheese.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cheeseMouseDragged(evt);
            }
        });
        cheese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cheeseMousePressed(evt);
            }
        });
        jPanel4.add(cheese);
        cheese.setBounds(490, 420, 65, 49);

        pettey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/meat.png"))); // NOI18N
        pettey.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                petteyMouseDragged(evt);
            }
        });
        pettey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                petteyMousePressed(evt);
            }
        });
        jPanel4.add(pettey);
        pettey.setBounds(700, 420, 64, 64);

        bottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/bunBottom.png"))); // NOI18N
        bottom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bottomMouseDragged(evt);
            }
        });
        bottom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bottomMousePressed(evt);
            }
        });
        jPanel4.add(bottom);
        bottom.setBounds(260, 420, 118, 59);

        cutting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/cutting-board128.png"))); // NOI18N
        jPanel4.add(cutting);
        cutting.setBounds(290, 220, 140, 128);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/new kitchen.PNG"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        //   mouse presssed and x, y coordinates of screen are stored
        xmouse1 = evt.getX();
        ymouse1 = evt.getY(); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int xdrag1 = evt.getXOnScreen();
        int ydrag1 = evt.getYOnScreen();
        x2 = xdrag1;
        y2 = ydrag1;// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseDragged

    private void topMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topMousePressed
          // when elem pressed clicks will be incremnted
        click++;
        if (t) {
            xmousetop = evt.getX();
            ymousetop = evt.getY();
            if (click == 1) {
                count++;
            }
        } else {
            count--;}// TODO add your handling code here:
    }//GEN-LAST:event_topMousePressed

    private void topMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topMouseDragged
        if (t) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            top.setLocation((x - x2) - (xmousetop - xmouse1), (y - y2) - (ymousetop - ymouse1));
            top.setVisible(true);

        }
        click = 0;// TODO add your handling code here:
    }//GEN-LAST:event_topMouseDragged

    private void cheeseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cheeseMousePressed
        click++;
        if (c) {
            xmousechee = evt.getX();
            ymousechee = evt.getY();
            if (click == 1) {
                count++;
            }
        } else {
            count--;
        }
// TODO add your handling code here:
    }//GEN-LAST:event_cheeseMousePressed

    private void cheeseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cheeseMouseDragged
        if (c) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            cheese.setLocation((x - x2) - (xmousechee - xmouse1), (y - y2) - (ymousechee - ymouse1));
            cheese.setVisible(true);
            b = true;
            p = true;
            c = true;
            t = true;
        }
        click = 0;// TODO add your handling code here:
    }//GEN-LAST:event_cheeseMouseDragged

    private void petteyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petteyMousePressed
        click++;
        if (p) {
            xmousepettey = evt.getX();
            ymousepettey = evt.getY();
            if (click == 1) {
                count++;
            }
        } else {
            count--;}// TODO add your handling code here:
    }//GEN-LAST:event_petteyMousePressed

    private void petteyMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petteyMouseDragged
        if (p) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            pettey.setLocation((x - x2) - (xmousepettey - xmouse1), (y - y2) - (ymousepettey - ymouse1));
            pettey.setVisible(true);
            b = true;
            p = true;
            c = true;
            t = false;

        }
        click = 0;// TODO add your handling code here:
    }//GEN-LAST:event_petteyMouseDragged

    private void bottomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottomMousePressed
        click++;
        if (b) {
            xmousebottom = evt.getX();
            ymousebottom = evt.getY();
            if (click == 1) {
                count++;
            }
        } else {
            count--;}// TODO add your handling code here:
    }//GEN-LAST:event_bottomMousePressed

    private void bottomMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottomMouseDragged
        if (b) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            bottom.setLocation((x - x2) - (xmousebottom - xmouse1), (y - y2) - (ymousebottom - ymouse1));
            bottom.setVisible(true);
            b = true;
            p = true;
            t = false;
            c = false;

        }
        click = 0; // TODO add your handling code here:
    }//GEN-LAST:event_bottomMouseDragged

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
         // if all the ingrediets true only then done button will be enabled
        if (b && p && t && c) {
            try {
                String urlDB = System.getProperty("user.dir").concat("\\records1.accdb");

            con = DriverManager.getConnection("jdbc:ucanaccess://" + urlDB + ";memory=true");
            st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery("select* from records");
               
                 while(rs.next()){
                PreparedStatement s = con.prepareStatement("UPDATE records SET Score=? where Name='"+ login.name +"'");
                
                  // successfully done 
                if (count > 0 && count < 4) {
                     s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                
                    Successful_score S = new Successful_score(count);
                    S.setVisible(true);
                    this.dispose();
                } 
                // looser
                else if (count <= 0) {
                     s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                    
                    // cond will store string according to menu name eg: fish burger so "f" 
                    cond = "f";
                    LooserFrame l = new LooserFrame(count, cond);
                    l.setVisible(true);
                   this.dispose();
                } 
                 // full score and winner
                else if (count > 3) {
                     s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                    
                    Winner w = new Winner();
                    w.setVisible(true);
                   this.dispose();
                }
                 }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            
                 finally{
        try {
            con.close();
             st.close();
              rs.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(BakedPlainPizza.class.getName()).log(Level.SEVERE, null, ex);
        } 
       
        }}
    }//GEN-LAST:event_doneActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        BurgerMenu mf = new BurgerMenu();

        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fishburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fishburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fishburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fishburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fishburger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bottom;
    private javax.swing.JLabel cheese;
    private javax.swing.JLabel cutting;
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel pettey;
    private javax.swing.JLabel top;
    // End of variables declaration//GEN-END:variables
}
