/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CookingFun;

/**
 *
 * @author Hassan ul haq
 */
public class LooserFrame extends javax.swing.JFrame {

    // var for burger menu 
    boolean sb,fb,kb,pb;
// var for pizza menu 
    boolean plp,chp,pep;

    // var for cake menu 
    boolean sk,ck,bk;
    /**
     * Creates new form LooserFrame
     */
    public LooserFrame() {
        initComponents();
    }
    
    
     public LooserFrame(int count,String cond) {
         
       initComponents();
        if(count<0){
            count=0;
        score.setText(count+"");
        }  
        else
           score.setText(count+""); 
        
        
          // if user plays king burger then string will be k and in try again button only kb = true so king burger interface will be shown only
        if(cond.equals("k")){         
        kb=true;
        }
        else if(cond.equals("s")){
        sb=true;
        }
        else if(cond.equals("f")){
        fb=true;
        }
        else if(cond.equals("p")){
        pb=true;
        }  else if(cond.equals("bk")){
        bk=true;
        }  else if(cond.equals("ck")){
        ck=true;
        }  else if(cond.equals("sk")){
        sk=true;
        }
            
     }      
      
     public LooserFrame( String cound) {
        initComponents();
        if(cound.equals("plp")){
            score.setText(0+"");
          plp=true;  
        }
        else if(cound.equals("pep")){
            score.setText(0+"");
            pep=true;
        }
        else if(cound.equals("chp")){
            score.setText(0+"");
           chp=true; 
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tryagain = new javax.swing.JButton();
        playagain = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        loose = new javax.swing.JLabel();
        score = new javax.swing.JButton();
        score_label = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tryagain.setBackground(new java.awt.Color(102, 153, 0));
        tryagain.setFont(new java.awt.Font("Vani", 3, 14)); // NOI18N
        tryagain.setForeground(new java.awt.Color(153, 255, 0));
        tryagain.setText("TRY AGAIN");
        tryagain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryagainActionPerformed(evt);
            }
        });
        jPanel1.add(tryagain);
        tryagain.setBounds(60, 270, 130, 70);

        playagain.setBackground(new java.awt.Color(102, 153, 0));
        playagain.setFont(new java.awt.Font("Vani", 3, 14)); // NOI18N
        playagain.setForeground(new java.awt.Color(153, 255, 0));
        playagain.setText("PLAY AGAIN");
        playagain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playagainActionPerformed(evt);
            }
        });
        jPanel1.add(playagain);
        playagain.setBounds(540, 110, 130, 70);

        cancel.setBackground(new java.awt.Color(102, 153, 0));
        cancel.setFont(new java.awt.Font("Vani", 3, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(153, 255, 0));
        cancel.setText("CLOSE");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel);
        cancel.setBounds(580, 210, 120, 60);

        loose.setBackground(new java.awt.Color(102, 204, 0));
        loose.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        loose.setForeground(new java.awt.Color(102, 204, 0));
        loose.setText("OOPS!! YOU LOOSE........");
        jPanel1.add(loose);
        loose.setBounds(230, 90, 280, 50);

        score.setBackground(new java.awt.Color(102, 153, 0));
        score.setFont(new java.awt.Font("Vani", 3, 18)); // NOI18N
        score.setForeground(new java.awt.Color(153, 255, 0));
        jPanel1.add(score);
        score.setBounds(110, 170, 110, 50);

        score_label.setBackground(new java.awt.Color(102, 204, 0));
        score_label.setFont(new java.awt.Font("Vani", 3, 14)); // NOI18N
        score_label.setForeground(new java.awt.Color(102, 204, 0));
        score_label.setText("SCORE:");
        jPanel1.add(score_label);
        score_label.setBounds(130, 130, 90, 30);

        background.setBackground(new java.awt.Color(255, 255, 204));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/13.PNG"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 760, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void playagainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playagainActionPerformed
        Start_Page  t=new Start_Page();
        t.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_playagainActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
         this.dispose(); 
    }//GEN-LAST:event_cancelActionPerformed

    private void tryagainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryagainActionPerformed
      // now only the particular frame will be shown on presseing try again button 
        if(kb){
        KingBurger  p=new KingBurger();
        p.setVisible(true);
        this.dispose();
       
       }
       else if(sb){
           SimpleBurger  s=new SimpleBurger();
        s.setVisible(true);
        this.dispose();
       }
       else if(fb){
        Fishburger  f=new Fishburger();
        f.setVisible(true);
        this.dispose();
       }
       else if(pb){
       PlainBURGER b = new PlainBURGER();
        b.setVisible(true);
       this.dispose();
       }
       else if(pep){
       PepperoniPizza pe= new PepperoniPizza();
        pe.setVisible(true);
       this.dispose();
       }
      else if(plp){
       PlainPizza pl = new PlainPizza();
        pl.setVisible(true);
       this.dispose();
       }
       else if(chp){
        ChickenPizza  ch = new  ChickenPizza();
        ch.setVisible(true);
        this.dispose();
       } 
       else if(bk){
        birthday bh = new birthday();
        bh.setVisible(true);
       this.dispose();
       } 
       else if(ck){
        Cupcake  cp = new  Cupcake();
        cp.setVisible(true);
       this.dispose();
       } 
       else if(sk){
        straw  st = new  straw();
        st.setVisible(true);
       this.dispose();
       }
    }//GEN-LAST:event_tryagainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LooserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LooserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LooserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LooserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LooserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loose;
    private javax.swing.JButton playagain;
    private javax.swing.JButton score;
    private javax.swing.JLabel score_label;
    private javax.swing.JButton tryagain;
    // End of variables declaration//GEN-END:variables
}
