/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CookingFun;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hassan ul haq
 */
public class PlainBURGER extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs;

    // these boolean var are used for enabling and disabling the ingredients(labels)

    boolean b, t, p, s, o;
    // score counting 
    protected int count;
    //  used for calculting the clicks on ingredient
    int click;
    
    // this var is used for looser frame's try again button 
    // we use it for transfering the string to looser frame 
    // suppose if user is playing on king burger interface and he lost with the score 0 and < 0 
    // then he want to try it again , for this purpose to show him the king burger interface again 
    // for this we are passing the string alphabet as the type of burger user is playing ,eg: for king "k" , for fish burger "f" etc
    // and then for making same burger again he will get the same interface again
    String cond;

     // mouse pressed on the scrren
    int xmouse1;
    int ymouse1;
    // mouse dragged on the screen 
    int x2;
    int y2;
    
    // mouse pressed on the object(ingredient)
    int xmousebottom;
    int ymousebottom;
    int xmousetop;
    int ymousetop;
    int xmouseonion;
    int ymouseonion;
    int xmousesalad;
    int ymousesalad;
    int xmousepettey;
    int ymousepettey;

    /**
     * Creates new form Plain
     */
    public PlainBURGER() {
        initComponents();
        click = 0;
        count = 0;
        b = true;
        t = false;

        p = false;
        s = false;

        o = false;

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        top = new javax.swing.JLabel();
        onion = new javax.swing.JLabel();
        salad = new javax.swing.JLabel();
        pattey = new javax.swing.JLabel();
        bottom = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        done = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        top.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/bun top.png"))); // NOI18N
        top.setText(" ");
        top.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topMouseDragged(evt);
            }
        });
        top.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topMousePressed(evt);
            }
        });
        jPanel1.add(top);
        top.setBounds(20, 410, 120, 70);

        onion.setBackground(new java.awt.Color(255, 204, 204));
        onion.setForeground(new java.awt.Color(255, 204, 204));
        onion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/imageedit_11_4840933673.png"))); // NOI18N
        onion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                onionMouseDragged(evt);
            }
        });
        onion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onionMousePressed(evt);
            }
        });
        jPanel1.add(onion);
        onion.setBounds(180, 420, 108, 50);

        salad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/salad.png"))); // NOI18N
        salad.setText(" ");
        salad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                saladMouseDragged(evt);
            }
        });
        salad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saladMousePressed(evt);
            }
        });
        jPanel1.add(salad);
        salad.setBounds(340, 420, 137, 61);

        pattey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/pettay.png"))); // NOI18N
        pattey.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                patteyMouseDragged(evt);
            }
        });
        pattey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patteyMousePressed(evt);
            }
        });
        jPanel1.add(pattey);
        pattey.setBounds(700, 420, 101, 60);

        bottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/bunBottom.png"))); // NOI18N
        bottom.setText(" ");
        bottom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bottomMouseDragged(evt);
            }
        });
        bottom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bottomMousePressed(evt);
            }
        });
        jPanel1.add(bottom);
        bottom.setBounds(520, 420, 125, 59);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/cutting-board128.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(320, 220, 140, 100);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        back.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(102, 255, 102));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/backYellow.PNG"))); // NOI18N
        back.setText(" ");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        done.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        done.setForeground(new java.awt.Color(153, 255, 102));
        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/doneYellow.PNG"))); // NOI18N
        done.setText(" ");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setText("BACK");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 102));
        jLabel9.setText("DONE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(680, 0, 180, 400);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/new kitchen.PNG"))); // NOI18N
        jLabel1.setText(" ");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-8, 0, 870, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
          // if all the ingrediets true only then done button will be enabled
        if (b && p && t && s && o) {
            try {
                String urlDB = System.getProperty("user.dir").concat("\\records1.accdb");

            con = DriverManager.getConnection("jdbc:ucanaccess://" + urlDB + ";memory=true");
            st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery("select* from records");
            
                 while(rs.next()){
                PreparedStatement s = con.prepareStatement("UPDATE records SET Score=? where Name='"+ login.name +"'");
               
                 // successfully done 
                if (count > 0 && count < 5) {
                     s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                    
                    Successful_score S = new Successful_score(count);
                    S.setVisible(true);
                   this.dispose();
                } 
                 // looser
                else if (count <= 0) {
                     s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                    
                     // cond will store string according to menu name eg: plain burger so "p" 
                    cond = "p";
                    LooserFrame l = new LooserFrame(count, cond);
                    l.setVisible(true);
                    this.dispose();
                } 
                  // full score and winner
                else if (count > 4) {
                     s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                    
                    Winner w = new Winner();
                    w.setVisible(true);
                    this.dispose();
                }
                 }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            
         finally{
        try {
            con.close();
             st.close();
              rs.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(BakedPlainPizza.class.getName()).log(Level.SEVERE, null, ex);
        } 
       
        }
        }

    }//GEN-LAST:event_doneActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        BurgerMenu mf = new BurgerMenu();
        mf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void topMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topMouseDragged
        if (t) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            top.setLocation((x - x2) - (xmousetop - xmouse1), (y - y2) - (ymousetop - ymouse1));
            top.setVisible(true);

        }
        click = 0;
    }//GEN-LAST:event_topMouseDragged

    private void topMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topMousePressed
         // when elem pressed clicks will be incremnted
        click++;
        if (t) {
            xmousetop = evt.getX();
            ymousetop = evt.getY();
            if (click == 1) {
                count++;
            }
        } else {
            count--;
        }
    }//GEN-LAST:event_topMousePressed

    private void onionMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onionMouseDragged
        if (o) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            onion.setLocation((x - x2) - (xmouseonion - xmouse1), (y - y2) - (ymouseonion - ymouse1));
            onion.setVisible(true);
            b = true;
            t = true;

            p = true;
            s = true;

            o = true;
        }
        click = 0;
    }//GEN-LAST:event_onionMouseDragged

    private void onionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onionMousePressed
        click++;
        if (o) {
            xmouseonion = evt.getX();
            ymouseonion = evt.getY();
            if (click == 1) {
                count++;
            }
        } else {
            count--;
        }
    }//GEN-LAST:event_onionMousePressed

    private void saladMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saladMouseDragged
        if (s) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            salad.setLocation((x - x2) - (xmousesalad - xmouse1), (y - y2) - (ymousesalad - ymouse1));
            salad.setVisible(true);
            b = true;
            t = false;

            p = true;
            s = true;

            o = true;
        }
        click = 0;
    }//GEN-LAST:event_saladMouseDragged

    private void saladMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saladMousePressed
        click++;
        if (s) {
            xmousesalad = evt.getX();
            ymousesalad = evt.getY();
            if (click == 1) {
                count++;
            }
        } else {
            count--;
        }
    }//GEN-LAST:event_saladMousePressed

    private void bottomMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottomMouseDragged
        if (b) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            bottom.setLocation((x - x2) - (xmousebottom - xmouse1), (y - y2) - (ymousebottom - ymouse1));
            bottom.setVisible(true);
            b = true;
            t = false;

            p = true;
            s = false;

            o = false;

        }
        click = 0;
    }//GEN-LAST:event_bottomMouseDragged

    private void bottomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottomMousePressed
        click++;
        if (b) {
            xmousebottom = evt.getX();
            ymousebottom = evt.getY();
            if (click == 1) {
                count++;
            }
        } else {
            count--;
        }
    }//GEN-LAST:event_bottomMousePressed

    private void patteyMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patteyMouseDragged
        if (p) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            pattey.setLocation((x - x2) - (xmousepettey - xmouse1), (y - y2) - (ymousepettey - ymouse1));
            pattey.setVisible(true);
            b = true;
            t = false;

            p = true;
            s = true;

            o = false;

        }
        click = 0;
    }//GEN-LAST:event_patteyMouseDragged

    private void patteyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patteyMousePressed
        click++;
        if (p) {
            xmousepettey = evt.getX();
            ymousepettey = evt.getY();
            if (click == 1) {
                count++;
            }
        } else {
            count--;
        }
    }//GEN-LAST:event_patteyMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
         //   mouse presssed and x, y coordinates of screen are stored
        xmouse1 = evt.getX();
        ymouse1 = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int xdrag1 = evt.getXOnScreen();
        int ydrag1 = evt.getYOnScreen();
        x2 = xdrag1;
        y2 = ydrag1;
    }//GEN-LAST:event_jLabel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlainBURGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlainBURGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlainBURGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlainBURGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlainBURGER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bottom;
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel onion;
    private javax.swing.JLabel pattey;
    private javax.swing.JLabel salad;
    private javax.swing.JLabel top;
    // End of variables declaration//GEN-END:variables
}
