/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CookingFun;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author toshiba
 */
public class straw extends javax.swing.JFrame {
    private Connection con;
    private Statement st;
    private ResultSet rs;
    
    boolean c,ca,g,ga,cr,s;
  protected int count;
   int click;
    String cond;
int xmouse1;
    int ymouse1;
    int x2;
    int y2;
    int xmousecake;
    int ymousecake;
    int xmousestrw;
    int ymousestrw;
    int xmousecre;
    int ymousecre;
    int xmousewhipcre;
    int ymousewhipcre;
    int xmouselargcake;
    int ymouselargcake;
    int xmouselargcre;
    int ymouselargcre;
    /**
     * Creates new form straw
     */
    public straw() {
        initComponents();
         click = 0;
        count = 0;
        c = true;
        ca = false;
       
        g = false;
        ga = false;
        
        cr = false;
        s=false;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        strw = new javax.swing.JLabel();
        cream = new javax.swing.JLabel();
        smallglaze = new javax.swing.JLabel();
        smallcake = new javax.swing.JLabel();
        largeglazee = new javax.swing.JLabel();
        largecake = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        done = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(null);

        strw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/straw.png"))); // NOI18N
        strw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                strwMouseDragged(evt);
            }
        });
        strw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                strwMousePressed(evt);
            }
        });
        jPanel1.add(strw);
        strw.setBounds(100, 390, 50, 50);

        cream.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/cream.png"))); // NOI18N
        cream.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                creamMouseDragged(evt);
            }
        });
        cream.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                creamMousePressed(evt);
            }
        });
        jPanel1.add(cream);
        cream.setBounds(480, 400, 50, 30);

        smallglaze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/sclg.png"))); // NOI18N
        smallglaze.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                smallglazeMouseDragged(evt);
            }
        });
        smallglaze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                smallglazeMousePressed(evt);
            }
        });
        jPanel1.add(smallglaze);
        smallglaze.setBounds(150, 370, 130, 80);

        smallcake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/scs.png"))); // NOI18N
        smallcake.setText("i");
        smallcake.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                smallcakeMouseDragged(evt);
            }
        });
        smallcake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                smallcakeMousePressed(evt);
            }
        });
        jPanel1.add(smallcake);
        smallcake.setBounds(380, 390, 98, 67);

        largeglazee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/scsg.png"))); // NOI18N
        largeglazee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                largeglazeeMouseDragged(evt);
            }
        });
        largeglazee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                largeglazeeMousePressed(evt);
            }
        });
        jPanel1.add(largeglazee);
        largeglazee.setBounds(250, 390, 130, 60);

        largecake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/scb.png"))); // NOI18N
        largecake.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                largecakeMouseDragged(evt);
            }
        });
        largecake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                largecakeMousePressed(evt);
            }
        });
        jPanel1.add(largecake);
        largecake.setBounds(540, 380, 130, 80);

        back.setBackground(new java.awt.Color(255, 255, 0));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(550, 60, 50, 50);

        done.setBackground(new java.awt.Color(255, 255, 0));
        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/done.png"))); // NOI18N
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        jPanel1.add(done);
        done.setBounds(550, 190, 54, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/cutting-board128.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 200, 128, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ab/Cap.PNG"))); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 30, 610, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
         if (ca && c && g && ga && cr && s) {            
             try {
                 String urlDB = System.getProperty("user.dir").concat("\\records1.accdb");

            con = DriverManager.getConnection("jdbc:ucanaccess://" + urlDB + ";memory=true");
            st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery("select* from records");
                  while(rs.next()){
                PreparedStatement s = con.prepareStatement("UPDATE records SET Score=? where Name='"+ login.name +"'");
             if (count > 0 && count<6) {
                s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                 
                 Successful_score S = new Successful_score(count);
                S.setVisible(true);
                 this.dispose();
            } else if(count<=0)
            {s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                    
                cond="sk";
                LooserFrame l = new LooserFrame(count,cond);
                l.setVisible(true);
                this.dispose();
            }else if(count>5)
               {s.setInt(1, count);
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(this, "score added");
                    
           Winner w= new Winner();
            w.setVisible(true);
            this.dispose();
     }
                  }   } catch (SQLException ex) {
                Logger.getLogger(SimpleBurger.class.getName()).log(Level.SEVERE, null, ex);
            }
             finally{
        try {
            rs = st.executeQuery("select* from records");
            con.close();
            rs.close();
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(BakedPlainPizza.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
        }
             
        // TODO add your handling code here:
    }//GEN-LAST:event_doneActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      CakeMenu pm = new CakeMenu();
         pm.setVisible(true);
       this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void strwMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_strwMousePressed
      click++;
      if(s){
        xmousestrw= evt.getX();
       ymousestrw =evt.getY(); // TODO add your handling code here:
       if(click==1)
           count++;
      }
      else
          count--;
    }//GEN-LAST:event_strwMousePressed

    private void strwMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_strwMouseDragged
        int x = evt.getXOnScreen();
          int y = evt.getYOnScreen();
         strw.setLocation((x-x2)-(xmousestrw-xmouse1), (y-y2)-(ymousestrw-ymouse1));
           strw.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_strwMouseDragged

    private void smallglazeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smallglazeMousePressed
      click++;
        if(ga){
        xmousecre= evt.getX();
       ymousecre =evt.getY(); // TODO add your handling code here:
       if(click==1)
           count++;
       }
       else
           count--;
    }//GEN-LAST:event_smallglazeMousePressed

    private void smallglazeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smallglazeMouseDragged
        if(ga){
        int x = evt.getXOnScreen();
          int y = evt.getYOnScreen();
         smallglaze.setLocation((x-x2)-(xmousecre-xmouse1), (y-y2)-(ymousecre-ymouse1));
           smallglaze.setVisible(true);// TODO add your handling code here:
            c = true;
        ca = true;
       
        g = true;
        ga = true;
        
        cr = true;
        s=false;
       }
       click=0;
    }//GEN-LAST:event_smallglazeMouseDragged

    private void largeglazeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_largeglazeeMousePressed
       click++;
       if(g){
        xmouselargcre= evt.getX();
       ymouselargcre =evt.getY(); // TODO add your handling code here:
       if(click==1)
           count++;
       }
       else
           count--;
    }//GEN-LAST:event_largeglazeeMousePressed

    private void largeglazeeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_largeglazeeMouseDragged
        if(g){
        int x = evt.getXOnScreen();
          int y = evt.getYOnScreen();
         largeglazee.setLocation((x-x2)-(xmouselargcre-xmouse1), (y-y2)-(ymouselargcre-ymouse1));
           largeglazee.setVisible(true);// TODO add your handling code here:
            c = true;
        ca = true;
       
        g = true;
        ga = false;
        
        cr = false;
        s=false;
       }
       click=0;
    }//GEN-LAST:event_largeglazeeMouseDragged

    private void smallcakeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smallcakeMousePressed
        click++;
        if(ca){
        xmousecake= evt.getX();
       ymousecake =evt.getY();
       if(click==1)
           count++;
        }
        else
            count--;
    }//GEN-LAST:event_smallcakeMousePressed

    private void smallcakeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smallcakeMouseDragged
        if(ca){
        int x = evt.getXOnScreen();
          int y = evt.getYOnScreen();
         smallcake.setLocation((x-x2)-(xmousecake-xmouse1), (y-y2)-(ymousecake-ymouse1));
           smallcake.setVisible(true);// TODO add your handling code here:
            c = true;
        ca = true;
       
        g = true;
        ga = true;
        
        cr = false;
        s=false;
       }
       click=0;
    }//GEN-LAST:event_smallcakeMouseDragged

    private void creamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creamMousePressed
        click++;
        if(cr){
        xmousewhipcre= evt.getX();
       ymousewhipcre =evt.getY();// TODO add your handling code here:
       if(click==1)
           count++;
        }
        else
            count--;
       
    }//GEN-LAST:event_creamMousePressed

    private void creamMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creamMouseDragged
        if(cr){
        int x = evt.getXOnScreen();
          int y = evt.getYOnScreen();
         cream.setLocation((x-x2)-(xmousewhipcre-xmouse1), (y-y2)-(ymousewhipcre-ymouse1));
           cream.setVisible(true);// TODO add your handling code here:
         c = true;
        ca = true;
       
        g = true;
        ga = true;
        
        cr = true;
        s=true;
       }
       click=0;
    }//GEN-LAST:event_creamMouseDragged

    private void largecakeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_largecakeMousePressed
       click++;
       if(c){
        xmouselargcake= evt.getX();
       ymouselargcake =evt.getY();
       if(click==1)
           count++;
       }
       else
           count--;
    }//GEN-LAST:event_largecakeMousePressed

    private void largecakeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_largecakeMouseDragged
       if(c){
        int x = evt.getXOnScreen();
          int y = evt.getYOnScreen();
         largecake.setLocation((x-x2)-(xmouselargcake-xmouse1), (y-y2)-(ymouselargcake-ymouse1));
           largecake.setVisible(true);// TODO add your handling code here:
           
        c = true;
        ca = false;
       
        g = true;
        ga = false;
        
        cr = false;
        s=false;
       }
       click=0;
    }//GEN-LAST:event_largecakeMouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
       xmouse1= evt.getX();
       ymouse1 =evt.getY(); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
         int xdrag1=evt.getXOnScreen();
            int ydrag1=evt.getYOnScreen();
             x2=xdrag1;
             y2=ydrag1;// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(straw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(straw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(straw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(straw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new straw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel cream;
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel largecake;
    private javax.swing.JLabel largeglazee;
    private javax.swing.JLabel smallcake;
    private javax.swing.JLabel smallglaze;
    private javax.swing.JLabel strw;
    // End of variables declaration//GEN-END:variables
}
