/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CookingFun;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author DR.SHER
 */
public class Successful_score extends javax.swing.JFrame {

    BufferedImage bg;

    /**
     * Creates new form Successful_score
     */
    public Successful_score() {
        try {
            bg = ImageIO.read(new File(System.getProperty("user.dir").concat("/src/IMAGES/Capture.PNG")));
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }
    
    public Successful_score(int count) {
        initComponents();
        
        if (count < 0) {
            count = 0;
            score.setText(count + "");
        } else {
            score.setText(count + "");
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                g.drawImage(bg,0,0,null);
            }
        };
        close = new javax.swing.JButton();
        playAgain = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        records = new javax.swing.JButton();
        score = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        close.setBackground(new java.awt.Color(102, 204, 0));
        close.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        close.setForeground(new java.awt.Color(51, 153, 0));
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(10, 270, 130, 36);

        playAgain.setBackground(new java.awt.Color(102, 204, 0));
        playAgain.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        playAgain.setForeground(new java.awt.Color(51, 153, 0));
        playAgain.setText("PLAY AGAIN");
        playAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainActionPerformed(evt);
            }
        });
        jPanel1.add(playAgain);
        playAgain.setBounds(10, 330, 150, 36);

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("SCORE:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 40, 70, 20);

        records.setBackground(new java.awt.Color(102, 204, 0));
        records.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        records.setForeground(new java.awt.Color(51, 153, 0));
        records.setText("RECORDS");
        records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordsActionPerformed(evt);
            }
        });
        jPanel1.add(records);
        records.setBounds(380, 10, 120, 31);

        score.setBackground(new java.awt.Color(51, 153, 0));
        score.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        score.setForeground(new java.awt.Color(204, 255, 102));
        jPanel1.add(score);
        score.setBounds(20, 70, 68, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Capture.PNG"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 510, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
      this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void playAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainActionPerformed
        Start_Page t = new Start_Page();
        t.setVisible(true);
       this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_playAgainActionPerformed

    private void recordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordsActionPerformed
        show_record sr = new show_record();
        sr.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_recordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Successful_score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Successful_score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Successful_score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Successful_score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Successful_score().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playAgain;
    private javax.swing.JButton records;
    private javax.swing.JButton score;
    // End of variables declaration//GEN-END:variables
}
